---
Name: approutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'login//$Action/$ID': '->admin'
    'register//$Action/$ID': 'App\Controllers\RegisterController'
    'ics//$Action/$ID/$Name': 'App\Controllers\ICSController'
    'app//$Action/$ID/$OtherID': 'App\Controllers\VueAppController'
    'api/v1/auth//$Action': 'App\Controllers\Api\AuthApiController'
    'api/v1/dashboard//$Action': 'App\Controllers\Api\DashboardApiController'
    'api/v1/announcements': 'App\Controllers\Api\AnnouncementsApiController'
    'api/v1/organizations//$Action/$ID': 'App\Controllers\Api\OrganizationsApiController'
    'api/v1/settings': 'App\Controllers\Api\SettingsApiController'
    'api/v1/register': 'App\Controllers\Api\RegisterApiController'
    'api/v1/maps//$Action/$ID': 'App\Controllers\Api\MapsApiController'
    'api/v1/food//$Action/$ID': 'App\Controllers\Api\FoodApiController'
    'api/v1/profile//$Action/$ID': 'App\Controllers\Api\ProfileApiController'
    'api/v1/calendar//$Action/$ID': 'App\Controllers\Api\CalendarApiController'
    'api/v1/scheduling-poll//$Action/$ID': 'App\Controllers\Api\SchedulingPollApiController'
    'api/v1/links//$Action/$ID': 'App\Controllers\Api\LinksApiController'
    'api/notifications//$Action': 'App\Controllers\NotificationApiController'
    'api/v1/tasks//$Action/$ID': 'App\Controllers\Api\TasksApiController'
    'api/v1/money//$Action/$ID': 'App\Controllers\Api\MoneyApiController'
    'api/v1/orgroles//$Action/$ID': 'App\Controllers\Api\OrgRolesApiController'
