---
Name: approutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'login//$Action/$ID': '->admin'
    'register//$Action/$ID': 'App\Controllers\RegisterController'
    'ics//$Action/$ID/$Name': 'App\Controllers\ICSController'
    'app//$Action/$ID/$OtherID': 'App\Controllers\VueAppController'
    'api/v1/auth//$Action': 'App\Controllers\Api\AuthApiController'
    'api/v1/dashboard//$Action': 'App\Controllers\Api\DashboardApiController'
    'api/v1/notices': 'App\Controllers\Api\NoticesApiController'
    'api/v1/calendar//$Action/$ID': 'App\Controllers\Api\CalendarApiController'
    'api/notifications//$Action': 'App\Controllers\NotificationApiController'
